### ISSUE TITLE
New Zen UI causes indicator to go past tab button edge

### ISSUE THREAD

**Issue by sjclayton** [benstone326/zen-browser-now-playing-indicator#3]
This issue affects the active tab and any tab that is playing media that is hovered.

Pretty self explanatory... here is an example.

![2024-09-24_00-57](https://github.com/user-attachments/assets/d297ab3d-2996-4c86-89ed-cabdc062d36e)

As you can see the indicator is now taller than the button height with the new Zen UI changes, which causes it to overhang past the button edge.

😁

**Comment by benstone326** [comment]
Commited to PR.
